site_name: Good Dae
nav:
  - Home: 'README.md'
markdown_extensions:
  - admonition
  - footnotes
  - markdown.extensions.attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: 'material'
